AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Description: >
  guardduty-threatlist-updater

  Regularly downloads and updates a guardduty threatlist from a source on the internet

Globals:
  Function:
    Timeout: 60

Parameters:
  S3Bucket:
    Type: String
  S3Key:
    Type: String
  GuardDutyDetectorId:
    Type: String
  ThreatIntelSetName:
    Type: String
    Default: AbuseCHIPBlocklist
  ThreatIntelURL:
    Type: String
    Default: https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt
  ThreatListFormat:
    Type: String
    Default: TXT
    AllowedValues:
      - TXT
      - STIX
      - OTX_CSV
      - ALIEN_VAULT
      - PROOF_POINT
      - FIRE_EYE
  UpdateSchedule:
    Type: String
    Default: "1 hour"
    AllowedPattern: "\\d+ (minute|hour|day)s?"

Resources:
  ThreatListUpdateFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: threatlist_updater/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          S3_KEY: !Ref S3Key
          GD_DETECTOR_ID: !Ref GuardDutyDetectorId
          GD_THREAT_INTEL_SET: !Ref ThreatIntelSetName
          THREATLIST_URL: !Ref ThreatIntelURL
          THREATLIST_FORMAT: !Ref ThreatListFormat
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AllowS3Actions
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${S3Bucket}/${S3Key}
            - Sid: AllowGuardDutyActions
              Effect: Allow
              Action:
                - guardduty:GetDetector
                - guardduty:GetThreatIntelSet
                - guardduty:CreateThreatIntelSet
                - guardduty:ListThreatIntelSets
                - guardduty:UpdateThreatIntelSet
              Resource: '*'
            - Sid: AllowPutIamRolePolicyGuardDuty
              Effect: Allow
              Action:
                - iam:PutRolePolicy
                #- iam:DeleteRolePolicy
              Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty
      Events:
        UpdateFnSchedule:
          Type: Schedule
          Properties:
            Schedule: !Sub "rate(${UpdateSchedule})"
            Enabled: true

Outputs:
  ThreatListUpdateFunction:
    Description: "ThreatList Update Lambda Function ARN"
    Value: !GetAtt ThreatListUpdateFn.Arn